name: Forecast Service
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Topic to read data from
    defaultValue: 3d-printer-data
    required: true
  - name: output
    inputType: OutputTopic
    description: Topic to send the forecasts
    defaultValue: forecast
    required: true
  - name: output_alerts
    inputType: OutputTopic
    description: Topic for sending alerts
    defaultValue: forecast-alerts
    required: true
  - name: parameter_name
    inputType: FreeText
    description: Name of the parameter for forecasting
    defaultValue: fluctuated_ambient_temperature
    required: false
  - name: debug
    inputType: FreeText
    description: Debug mode (1 enabled, 0 disabled)
    defaultValue: 0
    required: false
  - name: window_value
    inputType: FreeText
    description: Window value
    defaultValue: 1200
    required: true
  - name: window_type
    inputType: FreeText
    description: 1 for "Number of Observations", 2 for "Time Period"
    defaultValue: 1
    required: true
  - name: input_buffer_seconds
    inputType: FreeText
    description: Number of seconds of buffer to store input data. Forecast will be calculated each time the buffer is full
    defaultValue: 60
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
