name: Forecast Service
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: false
  - name: output
    inputType: OutputTopic
    description: Topic to send the forecasts
    defaultValue: forecast
    required: true
  - name: output_alerts
    inputType: OutputTopic
    description: Topic for sending alerts
    defaultValue: ''
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
