name: MQTT Test
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to publish to.
    defaultValue: mqtt-test
    required: true
  - name: mqtt_topic
    inputType: FreeText
    description: The root for messages in MQTT, this can be anything
    defaultValue: octoPrint/event/Zchange
    required: true
  - name: mqtt_server
    inputType: FreeText
    description: The address of your MQTT server
    defaultValue: 6f2f21257650402b8cfc45f06040ad79.s2.eu.hivemq.cloud
    required: true
  - name: mqtt_port
    inputType: FreeText
    description: The port of your MQTT instance
    defaultValue: 8883
    required: true
  - name: mqtt_username
    inputType: FreeText
    description: Your MQTT username
    defaultValue: mc2568
    required: true
  - name: mqtt_version
    inputType: FreeText
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
  - name: mqtt_password
    inputType: FreeText
    description: ''
    defaultValue: M3rl1n-06
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
