name: Data Smoothing
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: raw_data
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: smoothed-data
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
